# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetype',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
